apiVersion: v1
kind: Service
metadata:
  name: debate-service
  namespace: debate
spec:
  type: NodePort
  selector:
    app: debate-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
