apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: vllm-gpu
servers: 1
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  runtime:
    gpuRequest: all
env:
  - envVar: NVIDIA_VISIBLE_DEVICES=all
    nodeFilters:
      - server:*
  - envVar: NVIDIA_DRIVER_CAPABILITIES=all
    nodeFilters:
      - server:*
