apiVersion: v1
kind: Service
metadata:
  name: litellm-proxy
  namespace: litellm
spec:
  type: NodePort
  selector:
    app: litellm-proxy
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30400
