apiVersion: v1
kind: Service
metadata:
  name: sglang-mistral
  namespace: sglang
  labels:
    app: sglang-mistral
spec:
  type: NodePort
  selector:
    app: sglang-mistral
  ports:
  - name: http
    port: 30000
    targetPort: 30000
    nodePort: 30900
